// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEhy1grlr1wP-5epX946owuCl2r0fXSiw',
    appId: '1:181517513538:web:49493e3001a5df594a8edb',
    messagingSenderId: '181517513538',
    projectId: 'constructionconnect-cd419',
    authDomain: 'constructionconnect-cd419.firebaseapp.com',
    storageBucket: 'constructionconnect-cd419.firebasestorage.app',
    measurementId: 'G-VQ3LLDEB7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPsHZiTPchjlgGjc6AJfnTIWFMv2HruuU',
    appId: '1:181517513538:android:f2fe02637c66913e4a8edb',
    messagingSenderId: '181517513538',
    projectId: 'constructionconnect-cd419',
    storageBucket: 'constructionconnect-cd419.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnXaJFI47_7fzOG4A_m2X3Lgw-QpVT9q0',
    appId: '1:181517513538:ios:3b2d5d2e41746ac54a8edb',
    messagingSenderId: '181517513538',
    projectId: 'constructionconnect-cd419',
    storageBucket: 'constructionconnect-cd419.firebasestorage.app',
    iosBundleId: 'com.example.constructionConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnXaJFI47_7fzOG4A_m2X3Lgw-QpVT9q0',
    appId: '1:181517513538:ios:3b2d5d2e41746ac54a8edb',
    messagingSenderId: '181517513538',
    projectId: 'constructionconnect-cd419',
    storageBucket: 'constructionconnect-cd419.firebasestorage.app',
    iosBundleId: 'com.example.constructionConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEhy1grlr1wP-5epX946owuCl2r0fXSiw',
    appId: '1:181517513538:web:b97c051639e0d2c44a8edb',
    messagingSenderId: '181517513538',
    projectId: 'constructionconnect-cd419',
    authDomain: 'constructionconnect-cd419.firebaseapp.com',
    storageBucket: 'constructionconnect-cd419.firebasestorage.app',
    measurementId: 'G-BY2JB55LV2',
  );
}
